-- =====================================================================
-- ALPHA PULSE DATABASE AUDIT TRAIL SCHEMA (POSTGRESQL / SUPABASE)
-- Designed for tracking quantitative stock recommendation performance
-- and AI Agent execution logs.
-- =====================================================================

-- Enable UUID extension if supported
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create table 'recommendations' to store daily technical scan outputs
CREATE TABLE IF NOT EXISTS recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    scan_date DATE NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    exchange VARCHAR(10) NOT NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL', 'HOLD')),
    confidence_score INT NOT NULL CHECK (confidence_score BETWEEN 0 AND 100),
    grade VARCHAR(10) NOT NULL CHECK (grade IN ('Grade A', 'Grade B', 'Grade C')),
    price_close NUMERIC(12, 2) NOT NULL, -- Price in absolute VND
    buy_zone_min NUMERIC(12, 2) NOT NULL,
    buy_zone_max NUMERIC(12, 2) NOT NULL,
    stop_loss NUMERIC(12, 2) NOT NULL,
    target_1 NUMERIC(12, 2) NOT NULL,
    target_2 NUMERIC(12, 2) NOT NULL,
    risk_reward_ratio VARCHAR(20) NOT NULL,
    technical_rationale TEXT[] NOT NULL, -- Stored as text array for structured parsing
    execution_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes on recommendations for fast historical lookups
CREATE INDEX IF NOT EXISTS idx_recommendations_scan_date ON recommendations(scan_date DESC);
CREATE INDEX IF NOT EXISTS idx_recommendations_ticker ON recommendations(ticker);
CREATE INDEX IF NOT EXISTS idx_recommendations_grade ON recommendations(grade);

-- 2. Create table 'trade_logs' to track actual transaction execution and slip audits
CREATE TABLE IF NOT EXISTS trade_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    recommendation_id UUID REFERENCES recommendations(id) ON DELETE SET NULL,
    ticker VARCHAR(10) NOT NULL,
    entry_date DATE NOT NULL,
    entry_price NUMERIC(12, 2) NOT NULL, -- Actual execution price
    slippage_percent NUMERIC(5, 2), -- (entry_price - targetBuyPrice) / targetBuyPrice * 100
    price_t3 NUMERIC(12, 2), -- Price after T+3
    price_t5 NUMERIC(12, 2), -- Price after T+5
    price_t10 NUMERIC(12, 2), -- Price after T+10
    exit_date DATE,
    exit_price NUMERIC(12, 2),
    realized_pnl_percent NUMERIC(5, 2), -- Realized return
    outcome VARCHAR(10) CHECK (outcome IN ('WIN', 'LOSS', 'BREAKEVEN')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes on trade_logs for transaction audits
CREATE INDEX IF NOT EXISTS idx_trade_logs_ticker ON trade_logs(ticker);
CREATE INDEX IF NOT EXISTS idx_trade_logs_entry_date ON trade_logs(entry_date DESC);
CREATE INDEX IF NOT EXISTS idx_trade_logs_recommendation_id ON trade_logs(recommendation_id);

-- 3. Create view for slippage audit calibration
CREATE OR REPLACE VIEW view_slippage_audit AS
SELECT
    t.id AS trade_id,
    t.ticker,
    t.entry_date,
    t.entry_price,
    r.buy_zone_min,
    r.buy_zone_max,
    round(((t.entry_price - r.price_close) / r.price_close * 100), 2) AS close_slippage_percent,
    round(((t.entry_price - r.buy_zone_min) / r.buy_zone_min * 100), 2) AS min_zone_slippage_percent,
    t.price_t3,
    t.price_t5,
    t.price_t10,
    t.realized_pnl_percent,
    t.outcome
FROM trade_logs t
JOIN recommendations r ON t.recommendation_id = r.id;

-- Comment for tables
COMMENT ON TABLE recommendations IS 'Stores the historical daily end-of-day technical signals generated by Alpha Pulse.';
COMMENT ON TABLE trade_logs IS 'Tracks active trades executed by AI Agents or users to audit slippage and performance after T+3, T+5, T+10.';
