name: autofix.ci # needed to securely identify the workflow

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run lint/format scripts
        uses: area44/workflows/lint-format@7912709bf2aa6a2c6c03fddf2df233e7367234ce # v5.1.0

      - name: Run Ruff check (Python linter)
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "check"
          src: "scripts"

      - name: Run Ruff format (Python formatter)
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "format --check"
          src: "scripts"
