name: GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_run:
    workflows: ["Update Stock Data Daily"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run build
        uses: area44/workflows/vite@7912709bf2aa6a2c6c03fddf2df233e7367234ce # v5.1.0

  deploy:
    needs: build
    if: (github.event_name == 'push' || github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
